// Plant Data Module

const indoorPlants = [
    {
        id: "p_in_01",
        name: "Snake Plant",
        scientificName: "Sansevieria trifasciata",
        description: "A hardy succulent that grows tall, upright leaves with yellow edges. Excellent for bedroom air purification.",
        imageUrl: "https://images.unsplash.com/photo-1593482886870-9202a88e2c40",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "very-high",
        medicinalValues: ["Air purification", "Stress reduction"],
        advantages: ["Releases oxygen at night", "Tolerates neglect"],
        price: 25,
        type: "indoor"
    },
    {
        id: "p_in_02",
        name: "Spider Plant",
        scientificName: "Chlorophytum comosum",
        description: "Known for its arching leaves and baby plantlets. One of the easiest plants to grow.",
        imageUrl: "https://images.unsplash.com/photo-1572688484279-a9e8f75ebe0c",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Removes formaldehyde"],
        advantages: ["Fast growing", "Pet friendly"],
        price: 15,
        type: "indoor"
    },
    {
        id: "p_in_03",
        name: "Peace Lily",
        scientificName: "Spathiphyllum",
        description: "Features elegant white blooms and dark green leaves. Communicates thirst by drooping.",
        imageUrl: "https://images.unsplash.com/photo-1593691509543-c55ce32e01b5",
        idealTempMin: 18,
        idealTempMax: 26,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "very-high",
        medicinalValues: ["Removes mold spores"],
        advantages: ["Visual indicator for watering", "Flowering"],
        price: 30,
        type: "indoor"
    },
    {
        id: "p_in_04",
        name: "Aloe Vera",
        scientificName: "Aloe barbadensis miller",
        description: "Succulent with thick, fleshy leaves containing healing gel. Thrives on a sunny windowsill.",
        imageUrl: "https://images.unsplash.com/photo-1567331140054-3839d67562f8",
        idealTempMin: 13,
        idealTempMax: 27,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "high",
        medicinalValues: ["Treats burns", "Skin care"],
        advantages: ["Medicinal gel", "Drought tolerant"],
        price: 20,
        type: "indoor"
    },
    {
        id: "p_in_05",
        name: "Rubber Plant",
        scientificName: "Ficus elastica",
        description: "Large, glossy, dark green leaves. Can grow into a large indoor tree.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 15,
        idealTempMax: 28,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Air toxin removal"],
        advantages: ["Statement piece", "Robust structure"],
        price: 45,
        type: "indoor"
    },
    {
        id: "p_in_06",
        name: "ZZ Plant",
        scientificName: "Zamioculcas zamiifolia",
        description: "Waxy, smooth leaves that reflect light. Can survive in very low light and weeks without water.",
        imageUrl: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Air purification"],
        advantages: ["Indestructible", "Modern look"],
        price: 35,
        type: "indoor"
    },
    {
        id: "p_in_07",
        name: "English Ivy",
        scientificName: "Hedera helix",
        description: "Vigorous climber with evergreen foliage. Looks great in hanging baskets.",
        imageUrl: "https://images.unsplash.com/photo-1560717840-7756774a0045",
        idealTempMin: 10,
        idealTempMax: 25,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Reduces airborne mold"],
        advantages: ["Trailing growth", "Classic aesthetic"],
        price: 18,
        type: "indoor"
    },
    {
        id: "p_in_08",
        name: "Pothos",
        scientificName: "Epipremnum aureum",
        description: "Heart-shaped leaves that vine profusely. Extremely forgiving of various light conditions.",
        imageUrl: "https://images.unsplash.com/photo-1598512140411-dc4a42b00511",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "high",
        medicinalValues: ["Removes VOCs"],
        advantages: ["Easy propagation", "Trailing beauty"],
        price: 12,
        type: "indoor"
    },
    {
        id: "p_in_09",
        name: "Boston Fern",
        scientificName: "Nephrolepis exaltata",
        description: "Lush, feathery fronds. Adds a soft, tropical feel but needs high humidity.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 15,
        idealTempMax: 25,
        minHumidity: 70,
        sunlight: "medium",
        oxygenLevel: "very-high",
        medicinalValues: ["Humidifies air"],
        advantages: ["Non-toxic", "Lush greenery"],
        price: 22,
        type: "indoor"
    },
    {
        id: "p_in_10",
        name: "Areca Palm",
        scientificName: "Dypsis lutescens",
        description: "Bamboo-like stems with arching fronds. Great for adding height and tropical vibes.",
        imageUrl: "https://images.unsplash.com/photo-1610415664157-548c783c6b24",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "very-high",
        medicinalValues: ["Removes xylene/toluene"],
        advantages: ["Pet safe", "Large plant impact"],
        price: 55,
        type: "indoor"
    },
    {
        id: "p_in_11",
        name: "Monstera",
        scientificName: "Monstera deliciosa",
        description: "Famous for its large, fenestrated 'Swiss cheese' leaves. A fast-growing climber.",
        imageUrl: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Mood booster"],
        advantages: ["Iconic aesthetic", "Fast growth"],
        price: 45,
        type: "indoor"
    },
    {
        id: "p_in_12",
        name: "Fiddle Leaf Fig",
        scientificName: "Ficus lyrata",
        description: "Large, violin-shaped leaves. A popular design element but can be finicky.",
        imageUrl: "https://images.unsplash.com/photo-1597054232360-1e5b85e05a5a",
        idealTempMin: 18,
        idealTempMax: 28,
        minHumidity: 50,
        sunlight: "high",
        oxygenLevel: "high",
        medicinalValues: ["Air purifying"],
        advantages: ["Architectural shape", "Tree-like"],
        price: 60,
        type: "indoor"
    },
    {
        id: "p_in_13",
        name: "Chinese Evergreen",
        scientificName: "Aglaonema",
        description: "Patterned leaves in shades of green, silver, or red. Extremely durable.",
        imageUrl: "https://images.unsplash.com/photo-1616690248278-450cb25b6a7a",
        idealTempMin: 16,
        idealTempMax: 28,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Removes benzene"],
        advantages: ["Colorful foliage", "Low light tolerant"],
        price: 28,
        type: "indoor"
    },
    {
        id: "p_in_14",
        name: "Calathea Rattlesnake",
        scientificName: "Goeppertia insignis",
        description: "Striking patterns and purple undersides. Leaves fold up at night.",
        imageUrl: "https://images.unsplash.com/photo-1616690248166-5f1181822819",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 65,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None specific"],
        advantages: ["Decorative foliage", "Pet safe"],
        price: 32,
        type: "indoor"
    },
    {
        id: "p_in_15",
        name: "Philodendron Heartleaf",
        scientificName: "Philodendron hederaceum",
        description: "Classic trailing plant with deep green heart-shaped leaves.",
        imageUrl: "https://images.unsplash.com/photo-1612361734994-6d91cd4cb744",
        idealTempMin: 16,
        idealTempMax: 28,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Air cleaning"],
        advantages: ["Fast grower", "Easy care"],
        price: 15,
        type: "indoor"
    },
    {
        id: "p_in_16",
        name: "Jade Plant",
        scientificName: "Crassula ovata",
        description: "Tree-like succulent symbolizing good luck. Needs direct sun.",
        imageUrl: "https://images.unsplash.com/photo-1509304388383-ed5808ce4913",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["Traditional remedy"],
        advantages: ["Long lived", "Easy to prune"],
        price: 20,
        type: "indoor"
    },
    {
        id: "p_in_17",
        name: "Cast Iron Plant",
        scientificName: "Aspidistra elatior",
        description: "Named for its ability to survive nearly anything: low light, neglect, drafts.",
        imageUrl: "https://images.unsplash.com/photo-1611211232932-da3113c5b960",
        idealTempMin: 10,
        idealTempMax: 29,
        minHumidity: 30,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Virtually unkillable", "Broad leaves"],
        price: 40,
        type: "indoor"
    },
    {
        id: "p_in_18",
        name: "Bird of Paradise",
        scientificName: "Strelitzia nicolai",
        description: "Large, banana-like leaves that bring the tropics indoors. Needs bright light.",
        imageUrl: "https://images.unsplash.com/photo-1549416878-b97f805a96d1",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "high",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Dramatic statement", "Very tall"],
        price: 75,
        type: "indoor"
    },
    {
        id: "p_in_19",
        name: "String of Pearls",
        scientificName: "Senecio rowleyanus",
        description: "Succulent with cascading stems of pea-like beads. Unique and delicate.",
        imageUrl: "https://images.unsplash.com/photo-1589335668748-18e3290de004",
        idealTempMin: 15,
        idealTempMax: 28,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Unique texture", "Conversation starter"],
        price: 20,
        type: "indoor"
    },

    {
        id: "p_in_20",
        name: "Anthurium",
        scientificName: "Anthurium andraeanum",
        description: "Long-lasting, waxy red flowers (spathes) and glossy heart leaves.",
        imageUrl: "https://images.unsplash.com/photo-1614959542732-44677764a784",
        idealTempMin: 18,
        idealTempMax: 28,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Removes ammonia"],
        advantages: ["Blooms for months", "Colorful"],
        price: 35,
        type: "indoor"
    },
    {
        id: "p_in_21",
        name: "Bird's Nest Fern",
        scientificName: "Asplenium nidus",
        description: "Epiphytic fern with large, simple fronds resembling a nest.",
        imageUrl: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b",
        idealTempMin: 15,
        idealTempMax: 27,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Pet safe", "Unique shape"],
        price: 25,
        type: "indoor"
    },
    {
        id: "p_in_22",
        name: "Ponytail Palm",
        scientificName: "Beaucarnea recurvata",
        description: "Distinctive swollen trunk used for water storage with cascading leaves.",
        imageUrl: "https://images.unsplash.com/photo-1612361734994-6d91cd4cb744",
        idealTempMin: 10,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Drought tolerant", "Slow growing"],
        price: 45,
        type: "indoor"
    },
    {
        id: "p_in_23",
        name: "Dumb Cane",
        scientificName: "Dieffenbachia",
        description: "Large, variegated leaves in green and white cream. Toxic if ingested.",
        imageUrl: "https://images.unsplash.com/photo-1616690248278-450cb25b6a7a",
        idealTempMin: 16,
        idealTempMax: 27,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Air purification"],
        advantages: ["Fast growing", "Lush look"],
        price: 22,
        type: "indoor"
    },
    {
        id: "p_in_24",
        name: "Parlor Palm",
        scientificName: "Chamaedorea elegans",
        description: "Compact palm with feathery fronds. Popular since Victorian times.",
        imageUrl: "https://images.unsplash.com/photo-1610415664157-548c783c6b24",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 50,
        sunlight: "low",
        oxygenLevel: "high",
        medicinalValues: ["Removes benzene"],
        advantages: ["Pet safe", "Adapts to low light"],
        price: 20,
        type: "indoor"
    },
    {
        id: "p_in_25",
        name: "Arrowhead Plant",
        scientificName: "Syngonium podophyllum",
        description: "Leaves start arrow-shaped and become lobed as they mature.",
        imageUrl: "https://images.unsplash.com/photo-1598512140411-dc4a42b00511",
        idealTempMin: 16,
        idealTempMax: 29,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Easy care", "Diverse colors"],
        price: 15,
        type: "indoor"
    },
    {
        id: "p_in_26",
        name: "Peperomia",
        scientificName: "Peperomia obtusifolia",
        description: "Thick, rubbery leaves. Compact and easy to grow.",
        imageUrl: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 40,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Pet safe", "Desk plant"],
        price: 12,
        type: "indoor"
    },
    {
        id: "p_in_27",
        name: "Prayer Plant",
        scientificName: "Maranta leuconeura",
        description: "Leaves fold up at night like praying hands. Stunning patterns.",
        imageUrl: "https://images.unsplash.com/photo-1616690248166-5f1181822819",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Non-toxic", "Active movement"],
        price: 25,
        type: "indoor"
    },
    {
        id: "p_in_28",
        name: "Yucca",
        scientificName: "Yucca elephantipes",
        description: "Bold, sword-shaped leaves on woody canes. Very architectural.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 10,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Drought tolerant", "Vertical accent"],
        price: 55,
        type: "indoor"
    },
    {
        id: "p_in_29",
        name: "Money Tree",
        scientificName: "Pachira aquatica",
        description: "Braided trunk and palmate leaves. Symbol of prosperity.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 16,
        idealTempMax: 27,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Pet safe", "Good luck gift"],
        price: 45,
        type: "indoor"
    },
    {
        id: "p_in_30",
        name: "Dracaena Marginata",
        scientificName: "Dracaena marginata",
        description: "Spiky leaves on slender stems. Resembles a dragon tree.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 15,
        idealTempMax: 27,
        minHumidity: 40,
        sunlight: "medium",
        oxygenLevel: "very-high",
        medicinalValues: ["Removes xylene"],
        advantages: ["Modern look", "Easy care"],
        price: 30,
        type: "indoor"
    },
    {
        id: "p_in_31",
        name: "Hoya Heart",
        scientificName: "Hoya kerrii",
        description: "Single heart-shaped leaf often sold as a novelty.",
        imageUrl: "https://images.unsplash.com/photo-1589335668748-18e3290de004",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 40,
        sunlight: "high",
        oxygenLevel: "low",
        medicinalValues: ["None"],
        advantages: ["Romantic gift", "Succulent"],
        price: 15,
        type: "indoor"
    },
    {
        id: "p_in_32",
        name: "Begonia Maculata",
        scientificName: "Begonia maculata",
        description: "Polka dot begonia with angel wing leaves and red undersides.",
        imageUrl: "https://images.unsplash.com/photo-1616690248166-5f1181822819", // Reused pattern leaf
        idealTempMin: 18,
        idealTempMax: 25,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Striking foliage", "Unique"],
        price: 35,
        type: "indoor"
    },
    {
        id: "p_in_33",
        name: "Schefflera",
        scientificName: "Schefflera arboricola",
        description: "Umbrella palm with whorls of leaves. Can become bushy.",
        imageUrl: "https://images.unsplash.com/photo-1597054232360-1e5b85e05a5a",
        idealTempMin: 15,
        idealTempMax: 27,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Detoxifies air"],
        advantages: ["Fast grower", "Easy to shape"],
        price: 40,
        type: "indoor"
    },
    {
        id: "p_in_34",
        name: "Croton",
        scientificName: "Codiaeum variegatum",
        description: "Spectacular colorful leaves in yellow, orange, and red.",
        imageUrl: "https://images.unsplash.com/photo-1616690248278-450cb25b6a7a",
        idealTempMin: 15,
        idealTempMax: 29,
        minHumidity: 60,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Vibrant color", "Tropical feel"],
        price: 25,
        type: "indoor"
    },
    {
        id: "p_in_35",
        name: "African Violet",
        scientificName: "Saintpaulia",
        description: "Fuzzy leaves and purple/pink flowers. Blooms continuously indoors.",
        imageUrl: "https://images.unsplash.com/photo-1593482886870-9202a88e2c40",
        idealTempMin: 18,
        idealTempMax: 24,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Pet safe", "Constant blooms"],
        price: 10,
        type: "indoor"
    },
    {
        id: "p_in_36",
        name: "Air Plant",
        scientificName: "Tillandsia",
        description: "Plants that need no soil, absorbing moisture through leaves.",
        imageUrl: "https://images.unsplash.com/photo-1589335668748-18e3290de004",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "low",
        medicinalValues: ["None"],
        advantages: ["No dirt", "Creative display"],
        price: 8,
        type: "indoor"
    },
    {
        id: "p_in_37",
        name: "Kalanchoe",
        scientificName: "Kalanchoe blossfeldiana",
        description: "Succulent with sprays of small, bright flowers.",
        imageUrl: "https://images.unsplash.com/photo-1509304388383-ed5808ce4913",
        idealTempMin: 15,
        idealTempMax: 29,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["Wound healing"],
        advantages: ["Long bloom", "Low water"],
        price: 12,
        type: "indoor"
    },
    {
        id: "p_in_38",
        name: "Asparagus Fern",
        scientificName: "Asparagus setaceus",
        description: "Soft, misty green foliage. Not a true fern.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 15,
        idealTempMax: 25,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Delicate texture", "Fast growing"],
        price: 15,
        type: "indoor"
    },
    {
        id: "p_in_39",
        name: "Elephant Ear",
        scientificName: "Colocasia",
        description: "Giant, heart-shaped leaves that create a jungle vibe.",
        imageUrl: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 70,
        sunlight: "high",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Huge size", "Statement"],
        price: 50,
        type: "indoor"
    },
    {
        id: "p_in_40",
        name: "Weeping Fig",
        scientificName: "Ficus benjamina",
        description: "Graceful tree with drooping branches. Improved indoor air quality.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 50,
        sunlight: "high",
        oxygenLevel: "very-high",
        medicinalValues: ["None"],
        advantages: ["Tree form", "Elegant"],
        price: 45,
        type: "indoor"
    },
    {
        id: "p_in_41",
        name: "Aglaonema 'Lipstick'",
        scientificName: "Aglaonema 'Lipstick'",
        description: "Stunning foliage with bright red edges. Very popular in Indian homes for its color.",
        imageUrl: "https://images.unsplash.com/photo-1616690248278-450cb25b6a7a",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Air purification"],
        advantages: ["Vibrant color", "Low maintenance"],
        price: 350,
        type: "indoor"
    },
    {
        id: "p_in_42",
        name: "Dieffenbachia 'Camilla'",
        scientificName: "Dieffenbachia seguine",
        description: "Large cream and green leaves. Thrives in warm Indian interiors.",
        imageUrl: "https://images.unsplash.com/photo-1616690248278-450cb25b6a7a",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Lush tropical look", "Fast growth"],
        price: 250,
        type: "indoor"
    },
    {
        id: "p_in_43",
        name: "Song of India",
        scientificName: "Dracaena reflexa",
        description: "Twisted leaves with yellow stripes. A classic Indian ornamental plant.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 18,
        idealTempMax: 32,
        minHumidity: 40,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Air purifying", "Removes Xylene"],
        advantages: ["Hardy", "Slow growing beauty"],
        price: 300,
        type: "indoor"
    },
    {
        id: "p_in_44",
        name: "Philodendron 'Ceylon Golden'",
        scientificName: "Philodendron erubescens",
        description: "Neon yellow-green leaves. Adds a bright pop of color to shaded verandas.",
        imageUrl: "https://images.unsplash.com/photo-1612361734994-6d91cd4cb744",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Air cleaning"],
        advantages: ["Bright foliage", "Climber"],
        price: 150,
        type: "indoor"
    },
    {
        id: "p_in_45",
        name: "Money Plant 'Marble Queen'",
        scientificName: "Epipremnum aureum",
        description: "Variegated white and green leaves. Believed to bring prosperity in Vastu.",
        imageUrl: "https://images.unsplash.com/photo-1598512140411-dc4a42b00511",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "high",
        medicinalValues: ["Pollutant removal"],
        advantages: ["Good luck", "Cannot look bad"],
        price: 120,
        type: "indoor"
    },
    {
        id: "p_in_46",
        name: "Syngonium 'Pink Splash'",
        scientificName: "Syngonium podophyllum",
        description: "Arrowhead plant with pink speckles. Very trendy in Bangalore nurseries.",
        imageUrl: "https://images.unsplash.com/photo-1598512140411-dc4a42b00511",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Pink aesthetic", "Bushy growth"],
        price: 180,
        type: "indoor"
    },
    {
        id: "p_in_47",
        name: "Caladium 'Heart of Jesus'",
        scientificName: "Caladium bicolor",
        description: "Papery thin leaves with vibrant red/pink patterns. Loves Kerala humidity.",
        imageUrl: "https://images.unsplash.com/photo-1616690248166-5f1181822819",
        idealTempMin: 22,
        idealTempMax: 35,
        minHumidity: 70,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Showy", "Tuberous"],
        price: 200,
        type: "indoor"
    },
    {
        id: "p_in_48",
        name: "Bamboo Palm",
        scientificName: "Chamaedorea seifrizii",
        description: "Cluster forming palm that looks like bamboo. Great screen for balconies.",
        imageUrl: "https://images.unsplash.com/photo-1610415664157-548c783c6b24",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "very-high",
        medicinalValues: ["Top air purifier (NASA)"],
        advantages: ["Privacy screen", "Pet safe"],
        price: 450,
        type: "indoor"
    },
    {
        id: "p_in_49",
        name: "Fishtail Palm",
        scientificName: "Caryota mitis",
        description: "Leaves resemble a fish tail. Common in South Indian landscaping.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Unique leaf shape", "Tall"],
        price: 400,
        type: "indoor"
    },
    {
        id: "p_in_50",
        name: "Ming Aralia",
        scientificName: "Polyscias fruticosa",
        description: "Feathery, bonsai-like foliage. Elegant and artistic structure.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["Anti-inflammatory (Leaf tonic)"],
        advantages: ["Asian aesthetic", "Slow growing"],
        price: 350,
        type: "indoor"
    },
    {
        id: "p_in_51",
        name: "Croton 'Petra'",
        scientificName: "Codiaeum variegatum",
        description: "Bold leaves with yellow, red, and orange veins. 'Bangalore Croton'.",
        imageUrl: "https://images.unsplash.com/photo-1616690248278-450cb25b6a7a",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 60,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Color explosion", "Hedge potential"],
        price: 150,
        type: "indoor"
    },
    {
        id: "p_in_52",
        name: "Red Cordyline",
        scientificName: "Cordyline fruticosa",
        description: "Deep burgundy/pink leaves. Known locally as 'Good Luck Plant'.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 18,
        idealTempMax: 32,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Structural color", "Upright"],
        price: 200,
        type: "indoor"
    },
    {
        id: "p_in_53",
        name: "Maidenhair Fern",
        scientificName: "Adiantum",
        description: "Delicate, fan-shaped leaflets on black stems. Adored for its lacey look.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 18,
        idealTempMax: 28,
        minHumidity: 75,
        sunlight: "low",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Soft texture", "Terrarium suited"],
        price: 250,
        type: "indoor"
    },
    {
        id: "p_in_54",
        name: "Spider Plant 'Bonnie'",
        scientificName: "Chlorophytum comosum",
        description: "Curly variety of the classic Spider Plant. Compact and cute.",
        imageUrl: "https://images.unsplash.com/photo-1572688484279-a9e8f75ebe0c",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Air cleaning"],
        advantages: ["Curled leaves", "Hangable"],
        price: 150,
        type: "indoor"
    },
    {
        id: "p_in_55",
        name: "Snake Plant 'Laurentii'",
        scientificName: "Sansevieria trifasciata",
        description: "Yellow-edged sword leaves. The most durable plant for Indian heat.",
        imageUrl: "https://images.unsplash.com/photo-1593482886870-9202a88e2c40",
        idealTempMin: 15,
        idealTempMax: 40,
        minHumidity: 30,
        sunlight: "low",
        oxygenLevel: "very-high",
        medicinalValues: ["Night oxygen"],
        advantages: ["Indestructible", "Modern"],
        price: 200,
        type: "indoor"
    },
    {
        id: "p_in_56",
        name: "Asparagus Fern",
        scientificName: "Asparagus densiflorus",
        description: "Bright green, needle-like leaves. Cascades beautifully from pots.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 18,
        idealTempMax: 32,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Fast filler", "Textural contrast"],
        price: 150,
        type: "indoor"
    },
    {
        id: "p_in_57",
        name: "ZZ Raven",
        scientificName: "Zamioculcas zamiifolia",
        description: "Rare variety with nearly black leaves. Very stylish and premium.",
        imageUrl: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361",
        idealTempMin: 18,
        idealTempMax: 35,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Black foliage", "Trendy"],
        price: 800,
        type: "indoor"
    },
    {
        id: "p_in_58",
        name: "Lucky Bamboo",
        scientificName: "Dracaena sanderiana",
        description: "Stalks grown in water. A staple gift for Feng Shui and positivity.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 18,
        idealTempMax: 32,
        minHumidity: 50,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Positive energy"],
        advantages: ["Hydroponic", "Giftable"],
        price: 150,
        type: "indoor"
    },
    {
        id: "p_in_59",
        name: "Anthurium 'Red'",
        scientificName: "Anthurium andraeanum",
        description: "Classic red waxy flower. Long-lasting blooms for indoor tables.",
        imageUrl: "https://images.unsplash.com/photo-1614959542732-44677764a784",
        idealTempMin: 20,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Flowers indoors", "Air cleaner"],
        price: 450,
        type: "indoor"
    },
    {
        id: "p_in_60",
        name: "Peace Lily 'Sensation'",
        scientificName: "Spathiphyllum",
        description: "A giant variety with massive leaves. Fills corners perfectly.",
        imageUrl: "https://images.unsplash.com/photo-1593691509543-c55ce32e01b5",
        idealTempMin: 20,
        idealTempMax: 32,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "very-high",
        medicinalValues: ["Mold spore removal"],
        advantages: ["Huge size", "Statement"],
        price: 600,
        type: "indoor"
    }
];

const outdoorPlants = [
    // ... Previous Outdoor [1-19] ... 
    // Reinserting the last one and appending...
    {
        id: "p_out_20",
        name: "Thyme",
        scientificName: "Thymus vulgaris",
        description: "Low-growing woody herb. Excellent ground cover.",
        imageUrl: "https://images.unsplash.com/photo-1629158654877-2c5544d67310",
        idealTempMin: -5,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Antiseptic", "Respiratory aid"],
        advantages: ["Culinary", "Ground cover"],
        price: 6,
        type: "outdoor"
    },
    {
        id: "p_out_21",
        name: "Coneflower",
        scientificName: "Echinacea purpurea",
        description: "Purple daisy-like flowers with raised centers. Native to prairies.",
        imageUrl: "https://images.unsplash.com/photo-1595124036814-725f543666b6",
        idealTempMin: -10,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Immune boost"],
        advantages: ["Attracts butterflies", "Drought resistant"],
        price: 10,
        type: "outdoor"
    },
    {
        id: "p_out_22",
        name: "Bleeding Heart",
        scientificName: "Lamprocapnos spectabilis",
        description: "Arching stems with heart-shaped pink/white flowers.",
        imageUrl: "https://images.unsplash.com/photo-1616787688001-5256e6328362",
        idealTempMin: -15,
        idealTempMax: 25,
        minHumidity: 50,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Unique flower shape", "Shade lover"],
        price: 18,
        type: "outdoor"
    },
    {
        id: "p_out_23",
        name: "Dahlia",
        scientificName: "Dahlia pinnata",
        description: "Bushy tuberous plants with magnificent, diverse blooms.",
        imageUrl: "https://images.unsplash.com/photo-1593883344654-706599ccb20e",
        idealTempMin: 10,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Showstopper blooms", "Cut flowers"],
        price: 12,
        type: "outdoor"
    },
    {
        id: "p_out_24",
        name: "Morning Glory",
        scientificName: "Ipomoea",
        description: "Vines with trumpet-shaped flowers that open in the morning.",
        imageUrl: "https://images.unsplash.com/photo-1593883344654-706599ccb20e",
        idealTempMin: 10,
        idealTempMax: 35,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Fast climber", "Colorful"],
        price: 5,
        type: "outdoor"
    },
    {
        id: "p_out_25",
        name: "Wisteria",
        scientificName: "Wisteria sinensis",
        description: "Woody vine with cascading clusters of purple flowers.",
        imageUrl: "https://images.unsplash.com/photo-1557997380-a6df40345097",
        idealTempMin: -10,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Romantic aesthetic", "Fragrant"],
        price: 45,
        type: "outdoor"
    },
    {
        id: "p_out_26",
        name: "Peony",
        scientificName: "Paeonia",
        description: "Large, ruffled, fragrant flowers. A spring classic.",
        imageUrl: "https://images.unsplash.com/photo-1595124036814-725f543666b6",
        idealTempMin: -20,
        idealTempMax: 25,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["Anti-inflammatory"],
        advantages: ["Long lived", "Fragrance"],
        price: 35,
        type: "outdoor"
    },
    {
        id: "p_out_27",
        name: "Snapdragon",
        scientificName: "Antirrhinum",
        description: "Spikes of flowers that look like dragon mouths.",
        imageUrl: "https://images.unsplash.com/photo-1601655823671-6c2e7cc187d9",
        idealTempMin: 5,
        idealTempMax: 25,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Cool season color", "Children love them"],
        price: 6,
        type: "outdoor"
    },
    {
        id: "p_out_28",
        name: "Pansy",
        scientificName: "Viola tricolor",
        description: "Colorful flowers with 'faces'. Thrives in cooler weather.",
        imageUrl: "https://images.unsplash.com/photo-1593883344654-706599ccb20e",
        idealTempMin: 0,
        idealTempMax: 20,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["Edible"],
        advantages: ["Winter color", "Edible"],
        price: 4,
        type: "outdoor"
    },
    {
        id: "p_out_29",
        name: "Zinnia",
        scientificName: "Zinnia elegans",
        description: "Bright, daisy-like annuals. Very easy to grow from seed.",
        imageUrl: "https://images.unsplash.com/photo-1594957388796-0275825318db",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Heat tolerant", "Butterfly magnet"],
        price: 5,
        type: "outdoor"
    },
    {
        id: "p_out_30",
        name: "Begonia (Outdoor)",
        scientificName: "Begonia semperflorens",
        description: "Wax begonias perfect for shady bedding borders.",
        imageUrl: "https://images.unsplash.com/photo-1616690248166-5f1181822819",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Shade tolerance", "Continuous bloom"],
        price: 8,
        type: "outdoor"
    },
    {
        id: "p_out_31",
        name: "Salvia",
        scientificName: "Salvia splendens",
        description: "Spikes of intense red or purple tubular flowers.",
        imageUrl: "https://images.unsplash.com/photo-1593006856011-8e994967396a",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Attracts hummingbirds", "Heat tolerant"],
        price: 8,
        type: "outdoor"
    },
    {
        id: "p_out_32",
        name: "Impatiens",
        scientificName: "Impatiens walleriana",
        description: "Popular shade annual with non-stop blooming.",
        imageUrl: "https://images.unsplash.com/photo-1593883344654-706599ccb20e",
        idealTempMin: 10,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Brightens shade", "Easy"],
        price: 5,
        type: "outdoor"
    },
    {
        id: "p_out_33",
        name: "Coleus",
        scientificName: "Plectranthus scutellarioides",
        description: "Grown for its incredibly colorful foliage, not flowers.",
        imageUrl: "https://images.unsplash.com/photo-1616690248278-450cb25b6a7a",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Amazing patterns", "Good for pots"],
        price: 12,
        type: "outdoor"
    },
    {
        id: "p_out_34",
        name: "Canna Lily",
        scientificName: "Canna",
        description: "Tropical-looking plant with broad leaves and bright flowers.",
        imageUrl: "https://images.unsplash.com/photo-1549416878-b97f805a96d1",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 60,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Height", "Structural"],
        price: 18,
        type: "outdoor"
    },
    {
        id: "p_out_35",
        name: "Daylily",
        scientificName: "Hemerocallis",
        description: "Rugged perennials where each flower lasts one day.",
        imageUrl: "https://images.unsplash.com/photo-1595124036814-725f543666b6",
        idealTempMin: -10,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Edible flowers"],
        advantages: ["Tough", "Reliable"],
        price: 15,
        type: "outdoor"
    },
    {
        id: "p_out_36",
        name: "Butterfly Bush",
        scientificName: "Buddleja",
        description: "Shrub with spikes of flowers that attract pollinators.",
        imageUrl: "https://images.unsplash.com/photo-1596716075196-85c401345d31",
        idealTempMin: -5,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Wildlife friendly", "Fragrant"],
        price: 25,
        type: "outdoor"
    },
    {
        id: "p_out_37",
        name: "Lilac",
        scientificName: "Syringa",
        description: "Shrub famous for its spring scent and purple cone flowers.",
        imageUrl: "https://images.unsplash.com/photo-1596716075196-85c401345d31",
        idealTempMin: -20,
        idealTempMax: 25,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Nostalgic scent", "Cut flowers"],
        price: 30,
        type: "outdoor"
    },
    {
        id: "p_out_38",
        name: "Boxwood",
        scientificName: "Buxus",
        description: "Evergreen shrub mainly used for hedges and topiaries.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: -10,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Structure", "Formal look"],
        price: 35,
        type: "outdoor"
    },
    {
        id: "p_out_39",
        name: "Fuchsia",
        scientificName: "Fuchsia magellanica",
        description: "Dangling two-tone flowers that look like ballerinas.",
        imageUrl: "https://images.unsplash.com/photo-1557997380-a6df40345097",
        idealTempMin: 5,
        idealTempMax: 25,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Hanging baskets", "Unique"],
        price: 15,
        type: "outdoor"
    },
    {
        id: "p_out_40",
        name: "Chili Pepper",
        scientificName: "Capsicum annuum",
        description: "Bear hot or sweet peppers. Decorative and edible.",
        imageUrl: "https://images.unsplash.com/photo-1591466635338-790176dccb41",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Capsaicin"],
        advantages: ["Spice", "Ornamental fruit"],
        price: 8,
        type: "outdoor"
    },
    {
        id: "p_out_41",
        name: "Krishna Tulsi",
        scientificName: "Ocimum tenuiflorum",
        description: "Sacred purple-leaved basil. Essential for every Indian household courtyard.",
        imageUrl: "https://images.unsplash.com/photo-1629158654877-2c5544d67310",
        idealTempMin: 20,
        idealTempMax: 40,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "very-high",
        medicinalValues: ["Ayurvedic panacea", "Immunity boost"],
        advantages: ["Sacred", "Medicinal"],
        price: 50,
        type: "outdoor"
    },
    {
        id: "p_out_42",
        name: "Curry Leaf Plant",
        scientificName: "Murraya koenigii",
        description: "Aromatic leaves essential for South Indian cooking. Grows into a small tree.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 18,
        idealTempMax: 40,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Digestion", "Hair growth"],
        advantages: ["Culinary staple", "Self-seeding"],
        price: 80,
        type: "outdoor"
    },
    {
        id: "p_out_43",
        name: "Madurai Malli (Jasmine)",
        scientificName: "Jasminum sambac",
        description: "Famous GI-tagged Jasmine. Intensely fragrant white flowers used for Gajra.",
        imageUrl: "https://images.unsplash.com/photo-1558230230-67c00e65306d",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 60,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Stress relief"],
        advantages: ["Divine scent", "Cultural icon"],
        price: 150,
        type: "outdoor"
    },
    {
        id: "p_out_44",
        name: "Shoe Flower (Hibiscus)",
        scientificName: "Hibiscus rosa-sinensis",
        description: "Classic red hibiscus. Used for hair oil and temple offerings.",
        imageUrl: "https://images.unsplash.com/photo-1576435671569-425b0959f6d6",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 60,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Hair care", "Cooling"],
        advantages: ["Daily blooms", "Vibrant"],
        price: 120,
        type: "outdoor"
    },
    {
        id: "p_out_45",
        name: "Arali (Oleander)",
        scientificName: "Nerium oleander",
        description: "Hardy shrub with pink/white flowers. Common in medians and temples. Toxic.",
        imageUrl: "https://images.unsplash.com/photo-1557997380-a6df40345097",
        idealTempMin: 10,
        idealTempMax: 45,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None (Toxic)"],
        advantages: ["Drought proof", "Heavy bloomer"],
        price: 100,
        type: "outdoor"
    },
    {
        id: "p_out_46",
        name: "Nandiyavattai (Crape Jasmine)",
        scientificName: "Tabernaemontana divaricata",
        description: "White pinwheel flowers. Used for 'Archanai' in temples. Eyes wash medicinal use.",
        imageUrl: "https://images.unsplash.com/photo-1620067644342-997ad9264426",
        idealTempMin: 18,
        idealTempMax: 35,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["Eye care (Traditional)"],
        advantages: ["Moon garden", "White blooms"],
        price: 120,
        type: "outdoor"
    },
    {
        id: "p_out_47",
        name: "Idly Poo (Ixora)",
        scientificName: "Ixora coccinea",
        description: "Clusters of star-shaped red/orange flowers. Popular for hedging.",
        imageUrl: "https://images.unsplash.com/photo-1596716075196-85c401345d31",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Antiseptic roots"],
        advantages: ["Dense hedge", "Attracts butterflies"],
        price: 150,
        type: "outdoor"
    },
    {
        id: "p_out_48",
        name: "Vadamalli (Globe Amaranth)",
        scientificName: "Gomphrena globosa",
        description: "Purple globe-shaped flowers. Lasts forever, used in garlands.",
        imageUrl: "https://images.unsplash.com/photo-1593883344654-706599ccb20e",
        idealTempMin: 15,
        idealTempMax: 40,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Cough remedy"],
        advantages: ["Everlasting flower", "Cute"],
        price: 80,
        type: "outdoor"
    },
    {
        id: "p_out_49",
        name: "Kanakambaram",
        scientificName: "Crossandra infundibuliformis",
        description: "Bright orange apricot flowers. A staple for South Indian women's hair.",
        imageUrl: "https://images.unsplash.com/photo-1628557044797-f21a177c37ec",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Unique color", "Traditional"],
        price: 100,
        type: "outdoor"
    },
    {
        id: "p_out_50",
        name: " Paneer Rose",
        scientificName: "Rosa damascena",
        description: "The fragrant pink country rose. Used for rose water and gulkand.",
        imageUrl: "https://images.unsplash.com/photo-1595124036814-725f543666b6",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Skin toner", "Cooling"],
        advantages: ["Edible", "Fragrance"],
        price: 200,
        type: "outdoor"
    },
    {
        id: "p_out_51",
        name: "Mullai",
        scientificName: "Jasminum auriculatum",
        description: "Another Jasmine variety, blooms in evening. Essential for garlands.",
        imageUrl: "https://images.unsplash.com/photo-1558230230-67c00e65306d",
        idealTempMin: 18,
        idealTempMax: 32,
        minHumidity: 60,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Evening scent", "Vine"],
        price: 150,
        type: "outdoor"
    },
    {
        id: "p_out_52",
        name: "Shenbagam (Champak)",
        scientificName: "Magnolia champaca",
        description: "Golden yellow flowers with a heavenly fruity scent. Sacred tree.",
        imageUrl: "https://images.unsplash.com/photo-1549416878-b97f805a96d1",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 60,
        sunlight: "direct",
        oxygenLevel: "very-high",
        medicinalValues: ["Fever reducer"],
        advantages: ["Perfume", "Sacred"],
        price: 500,
        type: "outdoor"
    },
    {
        id: "p_out_53",
        name: "Parijatham (Coral Jasmine)",
        scientificName: "Nyctanthes arbor-tristis",
        description: "Night flowering jasmine with orange stems. Flowers fall at dawn.",
        imageUrl: "https://images.unsplash.com/photo-1593883344654-706599ccb20e",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Sciatica treatment"],
        advantages: ["Night scent", "Divine story"],
        price: 350,
        type: "outdoor"
    },
    {
        id: "p_out_54",
        name: "Manoranjitham",
        scientificName: "Artabotrys hexapetalus",
        description: "Climbing Ylang-Ylang. Flowers start green and turn yellow. Fruity scent.",
        imageUrl: "https://images.unsplash.com/photo-1616787688001-5256e6328362",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 70,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Aromatherapy"],
        advantages: ["Exotic scent", "Strong climber"],
        price: 400,
        type: "outdoor"
    },
    {
        id: "p_out_55",
        name: "Mango 'Amrapali'",
        scientificName: "Mangifera indica",
        description: "Dwarf mango variety suitable for large pots and terrace gardens.",
        imageUrl: "https://images.unsplash.com/photo-1595159339352-799da6960db8",
        idealTempMin: 20,
        idealTempMax: 40,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "very-high",
        medicinalValues: ["Leaves for diabetes"],
        advantages: ["King of fruits", "Dwarf"],
        price: 600,
        type: "outdoor"
    },
    {
        id: "p_out_56",
        name: "Guava (Allahabad Safeda)",
        scientificName: "Psidium guajava",
        description: "High yielding guava variety. Can be kept pruned in pots.",
        imageUrl: "https://images.unsplash.com/photo-1591466635338-790176dccb41",
        idealTempMin: 15,
        idealTempMax: 38,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Leaves for toothache"],
        advantages: ["Vitamin C power", "Easy fruit"],
        price: 300,
        type: "outdoor"
    },
    {
        id: "p_out_57",
        name: "Pomegranate 'Bhagwa'",
        scientificName: "Punica granatum",
        description: "Deep red seed variety. Very ornamental red flowers and fruits.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 15,
        idealTempMax: 40,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Antioxidant rich"],
        advantages: ["Decorative", "Healthy fruit"],
        price: 450,
        type: "outdoor"
    },
    {
        id: "p_out_58",
        name: "Lemon (Elumichai)",
        scientificName: "Citrus limon",
        description: "Local thin-skinned variety. Essential for rituals and cooking.",
        imageUrl: "https://images.unsplash.com/photo-1595159339352-799da6960db8",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Immunity"],
        advantages: ["Daily need", "Fragrant leaf"],
        price: 350,
        type: "outdoor"
    },
    {
        id: "p_out_59",
        name: "Neem",
        scientificName: "Azadirachta indica",
        description: "The village pharmacy. Can be grown as a bonsai/potted plant.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 10,
        idealTempMax: 45,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "very-high",
        medicinalValues: ["Antiviral", "Skin cure"],
        advantages: ["Air purifier", "Sacred"],
        price: 250,
        type: "outdoor"
    },
    {
        id: "p_out_60",
        name: "Betel Leaf (Karpoori)",
        scientificName: "Piper betle",
        description: "Spicy variety of paan. Climber that needs support.",
        imageUrl: "https://images.unsplash.com/photo-1612361734994-6d91cd4cb744",
        idealTempMin: 20,
        idealTempMax: 35,
        minHumidity: 70,
        sunlight: "low", // Actually likes shade/partial sun
        oxygenLevel: "high",
        medicinalValues: ["Digestion"],
        advantages: ["Cultural necessity", "Lush climber"],
        price: 150,
        type: "outdoor"
    }
];

module.exports = { indoorPlants, outdoorPlants };
