// Plant Data Module

const indoorPlants = [
    {
        id: "p_in_01",
        name: "Snake Plant",
        scientificName: "Sansevieria trifasciata",
        description: "A hardy succulent that grows tall, upright leaves with yellow edges. Excellent for bedroom air purification.",
        imageUrl: "https://images.unsplash.com/photo-1593482886870-9202a88e2c40",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "very-high",
        medicinalValues: ["Air purification", "Stress reduction"],
        advantages: ["Releases oxygen at night", "Tolerates neglect"],
        price: 25,
        type: "indoor"
    },
    {
        id: "p_in_02",
        name: "Spider Plant",
        scientificName: "Chlorophytum comosum",
        description: "Known for its arching leaves and baby plantlets. One of the easiest plants to grow.",
        imageUrl: "https://images.unsplash.com/photo-1572688484279-a9e8f75ebe0c",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Removes formaldehyde"],
        advantages: ["Fast growing", "Pet friendly"],
        price: 15,
        type: "indoor"
    },
    {
        id: "p_in_03",
        name: "Peace Lily",
        scientificName: "Spathiphyllum",
        description: "Features elegant white blooms and dark green leaves. Communicates thirst by drooping.",
        imageUrl: "https://images.unsplash.com/photo-1593691509543-c55ce32e01b5",
        idealTempMin: 18,
        idealTempMax: 26,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "very-high",
        medicinalValues: ["Removes mold spores"],
        advantages: ["Visual indicator for watering", "Flowering"],
        price: 30,
        type: "indoor"
    },
    {
        id: "p_in_04",
        name: "Aloe Vera",
        scientificName: "Aloe barbadensis miller",
        description: "Succulent with thick, fleshy leaves containing healing gel. Thrives on a sunny windowsill.",
        imageUrl: "https://images.unsplash.com/photo-1567331140054-3839d67562f8",
        idealTempMin: 13,
        idealTempMax: 27,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "high",
        medicinalValues: ["Treats burns", "Skin care"],
        advantages: ["Medicinal gel", "Drought tolerant"],
        price: 20,
        type: "indoor"
    },
    {
        id: "p_in_05",
        name: "Rubber Plant",
        scientificName: "Ficus elastica",
        description: "Large, glossy, dark green leaves. Can grow into a large indoor tree.",
        imageUrl: "https://images.unsplash.com/photo-1596720512803-085e481b4986",
        idealTempMin: 15,
        idealTempMax: 28,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Air toxin removal"],
        advantages: ["Statement piece", "Robust structure"],
        price: 45,
        type: "indoor"
    },
    {
        id: "p_in_06",
        name: "ZZ Plant",
        scientificName: "Zamioculcas zamiifolia",
        description: "Waxy, smooth leaves that reflect light. Can survive in very low light and weeks without water.",
        imageUrl: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Air purification"],
        advantages: ["Indestructible", "Modern look"],
        price: 35,
        type: "indoor"
    },
    {
        id: "p_in_07",
        name: "English Ivy",
        scientificName: "Hedera helix",
        description: "Vigorous climber with evergreen foliage. Looks great in hanging baskets.",
        imageUrl: "https://images.unsplash.com/photo-1560717840-7756774a0045",
        idealTempMin: 10,
        idealTempMax: 25,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Reduces airborne mold"],
        advantages: ["Trailing growth", "Classic aesthetic"],
        price: 18,
        type: "indoor"
    },
    {
        id: "p_in_08",
        name: "Pothos",
        scientificName: "Epipremnum aureum",
        description: "Heart-shaped leaves that vine profusely. Extremely forgiving of various light conditions.",
        imageUrl: "https://images.unsplash.com/photo-1598512140411-dc4a42b00511",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "high",
        medicinalValues: ["Removes VOCs"],
        advantages: ["Easy propagation", "Trailing beauty"],
        price: 12,
        type: "indoor"
    },
    {
        id: "p_in_09",
        name: "Boston Fern",
        scientificName: "Nephrolepis exaltata",
        description: "Lush, feathery fronds. Adds a soft, tropical feel but needs high humidity.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c",
        idealTempMin: 15,
        idealTempMax: 25,
        minHumidity: 70,
        sunlight: "medium",
        oxygenLevel: "very-high",
        medicinalValues: ["Humidifies air"],
        advantages: ["Non-toxic", "Lush greenery"],
        price: 22,
        type: "indoor"
    },
    {
        id: "p_in_10",
        name: "Areca Palm",
        scientificName: "Dypsis lutescens",
        description: "Bamboo-like stems with arching fronds. Great for adding height and tropical vibes.",
        imageUrl: "https://images.unsplash.com/photo-1610415664157-548c783c6b24",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "very-high",
        medicinalValues: ["Removes xylene/toluene"],
        advantages: ["Pet safe", "Large plant impact"],
        price: 55,
        type: "indoor"
    },
    {
        id: "p_in_11",
        name: "Monstera",
        scientificName: "Monstera deliciosa",
        description: "Famous for its large, fenestrated 'Swiss cheese' leaves. A fast-growing climber.",
        imageUrl: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Mood booster"],
        advantages: ["Iconic aesthetic", "Fast growth"],
        price: 45,
        type: "indoor"
    },
    {
        id: "p_in_12",
        name: "Fiddle Leaf Fig",
        scientificName: "Ficus lyrata",
        description: "Large, violin-shaped leaves. A popular design element but can be finicky.",
        imageUrl: "https://images.unsplash.com/photo-1597054232360-1e5b85e05a5a",
        idealTempMin: 18,
        idealTempMax: 28,
        minHumidity: 50,
        sunlight: "high",
        oxygenLevel: "high",
        medicinalValues: ["Air purifying"],
        advantages: ["Architectural shape", "Tree-like"],
        price: 60,
        type: "indoor"
    },
    {
        id: "p_in_13",
        name: "Chinese Evergreen",
        scientificName: "Aglaonema",
        description: "Patterned leaves in shades of green, silver, or red. Extremely durable.",
        imageUrl: "https://images.unsplash.com/photo-1616690248278-450cb25b6a7a",
        idealTempMin: 16,
        idealTempMax: 28,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Removes benzene"],
        advantages: ["Colorful foliage", "Low light tolerant"],
        price: 28,
        type: "indoor"
    },
    {
        id: "p_in_14",
        name: "Calathea Rattlesnake",
        scientificName: "Goeppertia insignis",
        description: "Striking patterns and purple undersides. Leaves fold up at night.",
        imageUrl: "https://images.unsplash.com/photo-1616690248166-5f1181822819",
        idealTempMin: 18,
        idealTempMax: 27,
        minHumidity: 65,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None specific"],
        advantages: ["Decorative foliage", "Pet safe"],
        price: 32,
        type: "indoor"
    },
    {
        id: "p_in_15",
        name: "Philodendron Heartleaf",
        scientificName: "Philodendron hederaceum",
        description: "Classic trailing plant with deep green heart-shaped leaves.",
        imageUrl: "https://images.unsplash.com/photo-1612361734994-6d91cd4cb744",
        idealTempMin: 16,
        idealTempMax: 28,
        minHumidity: 40,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["Air cleaning"],
        advantages: ["Fast grower", "Easy care"],
        price: 15,
        type: "indoor"
    },
    {
        id: "p_in_16",
        name: "Jade Plant",
        scientificName: "Crassula ovata",
        description: "Tree-like succulent symbolizing good luck. Needs direct sun.",
        imageUrl: "https://images.unsplash.com/photo-1509304388383-ed5808ce4913",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["Traditional remedy"],
        advantages: ["Long lived", "Easy to prune"],
        price: 20,
        type: "indoor"
    },
    {
        id: "p_in_17",
        name: "Cast Iron Plant",
        scientificName: "Aspidistra elatior",
        description: "Named for its ability to survive nearly anything: low light, neglect, drafts.",
        imageUrl: "https://images.unsplash.com/photo-1611211232932-da3113c5b960",
        idealTempMin: 10,
        idealTempMax: 29,
        minHumidity: 30,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Virtually unkillable", "Broad leaves"],
        price: 40,
        type: "indoor"
    },
    {
        id: "p_in_18",
        name: "Bird of Paradise",
        scientificName: "Strelitzia nicolai",
        description: "Large, banana-like leaves that bring the tropics indoors. Needs bright light.",
        imageUrl: "https://images.unsplash.com/photo-1549416878-b97f805a96d1",
        idealTempMin: 18,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "high",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Dramatic statement", "Very tall"],
        price: 75,
        type: "indoor"
    },
    {
        id: "p_in_19",
        name: "String of Pearls",
        scientificName: "Senecio rowleyanus",
        description: "Succulent with cascading stems of pea-like beads. Unique and delicate.",
        imageUrl: "https://images.unsplash.com/photo-1589335668748-18e3290de004",
        idealTempMin: 15,
        idealTempMax: 28,
        minHumidity: 30,
        sunlight: "high",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Unique texture", "Conversation starter"],
        price: 20,
        type: "indoor"
    },
    {
        id: "p_in_20",
        name: "Anthurium",
        scientificName: "Anthurium andraeanum",
        description: "Long-lasting, waxy red flowers (spathes) and glossy heart leaves.",
        imageUrl: "https://images.unsplash.com/photo-1614959542732-44677764a784",
        idealTempMin: 18,
        idealTempMax: 28,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["Removes ammonia"],
        advantages: ["Blooms for months", "Colorful"],
        price: 35,
        type: "indoor"
    }
];

const outdoorPlants = [
    {
        id: "p_out_01",
        name: "Marigold",
        scientificName: "Tagetes",
        description: "Bright orange/yellow flowers. Excellent natural pest deterrent.",
        imageUrl: "https://images.unsplash.com/photo-1588825656157-b4f0e5b7c7b8",
        idealTempMin: 10,
        idealTempMax: 35,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Antiseptic", "Wound healing"],
        advantages: ["Repels mosquitoes", "Edible petals"],
        price: 8,
        type: "outdoor"
    },
    {
        id: "p_out_02",
        name: "Lavender",
        scientificName: "Lavandula",
        description: "Fragrant purple spikes with silvery foliage. Loves sun and drainage.",
        imageUrl: "https://images.unsplash.com/photo-1596716075196-85c401345d31",
        idealTempMin: 5,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Calming", "Sleep aid"],
        advantages: ["Attracts bees", "Drought resistant"],
        price: 12,
        type: "outdoor"
    },
    {
        id: "p_out_03",
        name: "Rosemary",
        scientificName: "Salvia rosmarinus",
        description: "Woody, perennial herb with needle-like leaves and blue flowers.",
        imageUrl: "https://images.unsplash.com/photo-1593006856011-8e994967396a",
        idealTempMin: -5,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Memory boost", "Digestive aid"],
        advantages: ["Culinary herb", "Aromatic"],
        price: 15,
        type: "outdoor"
    },
    {
        id: "p_out_04",
        name: "Basil",
        scientificName: "Ocimum basilicum",
        description: "Tender annual herb essential for Italian and Asian cuisines.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c", // Reused generic green
        idealTempMin: 10,
        idealTempMax: 32,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Anti-inflammatory"],
        advantages: ["Fast growing", "Delicious"],
        price: 5,
        type: "outdoor"
    },
    {
        id: "p_out_05",
        name: "Tomato",
        scientificName: "Solanum lycopersicum",
        description: "Productive fruit-bearing plant. Needs support and regular water.",
        imageUrl: "https://images.unsplash.com/photo-1591466635338-790176dccb41",
        idealTempMin: 15,
        idealTempMax: 30,
        minHumidity: 60,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Lycopene source"],
        advantages: ["Homegrown produce", "Rewarding"],
        price: 6,
        type: "outdoor"
    },
    {
        id: "p_out_06",
        name: "Sunflower",
        scientificName: "Helianthus annuus",
        description: "Tall, iconic flower that tracks the sun. Produces edible seeds.",
        imageUrl: "https://images.unsplash.com/photo-1594957388796-0275825318db",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Attracts birds", "Cheerful"],
        price: 8,
        type: "outdoor"
    },
    {
        id: "p_out_07",
        name: "Hydrangea",
        scientificName: "Hydrangea macrophylla",
        description: "Large flower heads that change color based on soil pH.",
        imageUrl: "https://images.unsplash.com/photo-1595124036814-725f543666b6",
        idealTempMin: 5,
        idealTempMax: 25,
        minHumidity: 60,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Showy blooms", "Good for shade"],
        price: 35,
        type: "outdoor"
    },
    {
        id: "p_out_08",
        name: "Bougainvillea",
        scientificName: "Bougainvillea spectabilis",
        description: "Thorny vine with papery, brightly colored bracts. Heat lover.",
        imageUrl: "https://images.unsplash.com/photo-1557997380-a6df40345097",
        idealTempMin: 10,
        idealTempMax: 40,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Antiviral properties"],
        advantages: ["Constant color", "Drought tolerant"],
        price: 25,
        type: "outdoor"
    },
    {
        id: "p_out_09",
        name: "Jasmine",
        scientificName: "Jasminum officinale",
        description: "Vigorous climber with intensely fragrant white flowers.",
        imageUrl: "https://images.unsplash.com/photo-1558230230-67c00e65306d",
        idealTempMin: 5,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Relaxant", "Aphrodisiac"],
        advantages: ["Incredible scent", "Covers fences"],
        price: 20,
        type: "outdoor"
    },
    {
        id: "p_out_10",
        name: "Mint",
        scientificName: "Mentha",
        description: "Rapidly spreading herb with refreshing scent. Best in containers.",
        imageUrl: "https://images.unsplash.com/photo-1628557044797-f21a177c37ec",
        idealTempMin: 5,
        idealTempMax: 30,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["Digestive aid"],
        advantages: ["Tea making", "Pest repellent"],
        price: 5,
        type: "outdoor"
    },
    {
        id: "p_out_11",
        name: "Hibiscus",
        scientificName: "Hibiscus rosa-sinensis",
        description: "Tropical shrub with huge, trumpet-shaped flowers.",
        imageUrl: "https://images.unsplash.com/photo-1576435671569-425b0959f6d6",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 60,
        sunlight: "direct",
        oxygenLevel: "high",
        medicinalValues: ["Lower blood pressure (tea)"],
        advantages: ["Exotic look", "Continuous bloomer"],
        price: 22,
        type: "outdoor"
    },
    {
        id: "p_out_12",
        name: "Citrus Tree (Lemon)",
        scientificName: "Citrus limon",
        description: "Fruit tree with fragrant blossoms and edible fruit.",
        imageUrl: "https://images.unsplash.com/photo-1595159339352-799da6960db8",
        idealTempMin: 10,
        idealTempMax: 35,
        minHumidity: 50,
        sunlight: "direct",
        oxygenLevel: "very-high",
        medicinalValues: ["Vitamin C source"],
        advantages: ["Edible fruit", "Evergreen"],
        price: 45,
        type: "outdoor"
    },
    {
        id: "p_out_13",
        name: "Geranium",
        scientificName: "Pelargonium",
        description: "Popular bedding plant with clustered flowers. Drought tolerant.",
        imageUrl: "https://images.unsplash.com/photo-1534063264101-7b9071067202",
        idealTempMin: 5,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Antibacterial oil"],
        advantages: ["Long bloom season", "Vibrant colors"],
        price: 10,
        type: "outdoor"
    },
    {
        id: "p_out_14",
        name: "Hostas",
        scientificName: "Hosta",
        description: "Shade-loving perennials valued for their decorative foliage.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c?auto=format&fit=crop&w=700&q=60", // Generic foliage placeholder
        idealTempMin: -10,
        idealTempMax: 25,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Great for shade", "Lush texture"],
        price: 18,
        type: "outdoor"
    },
    {
        id: "p_out_15",
        name: "Gardenia",
        scientificName: "Gardenia jasminoides",
        description: "Shrub with creamy, intensely fragrant flowers and glossy leaves.",
        imageUrl: "https://images.unsplash.com/photo-1620067644342-997ad9264426",
        idealTempMin: 15,
        idealTempMax: 28,
        minHumidity: 70,
        sunlight: "medium",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Perfume scent", "Elegant"],
        price: 30,
        type: "outdoor"
    },
    {
        id: "p_out_16",
        name: "Petunia",
        scientificName: "Petunia",
        description: "Prolific bloomer available in nearly every color. Annual.",
        imageUrl: "https://images.unsplash.com/photo-1593883344654-706599ccb20e",
        idealTempMin: 10,
        idealTempMax: 30,
        minHumidity: 40,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Basket filler", "Cheap color"],
        price: 6,
        type: "outdoor"
    },
    {
        id: "p_out_17",
        name: "Azalea",
        scientificName: "Rhododendron",
        description: "Spring-blooming shrubs with masses of flowers.",
        imageUrl: "https://images.unsplash.com/photo-1616787688001-5256e6328362",
        idealTempMin: -5,
        idealTempMax: 25,
        minHumidity: 50,
        sunlight: "medium",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Spring color explosion", "Acid soil lover"],
        price: 25,
        type: "outdoor"
    },
    {
        id: "p_out_18",
        name: "Fern (Outdoor)",
        scientificName: "Polystichum",
        description: "Hardy ferns for shady garden spots.",
        imageUrl: "https://images.unsplash.com/photo-1596720512534-72210887ee2c?auto=format&fit=crop&w=700&q=60", // Generic fern
        idealTempMin: -10,
        idealTempMax: 25,
        minHumidity: 60,
        sunlight: "low",
        oxygenLevel: "high",
        medicinalValues: ["None"],
        advantages: ["Woodland look", "Low maintenance"],
        price: 15,
        type: "outdoor"
    },
    {
        id: "p_out_19",
        name: "Cosmos",
        scientificName: "Cosmos bipinnatus",
        description: "Daisy-like flowers on slender stems. Attracts butterflies.",
        imageUrl: "https://images.unsplash.com/photo-1601655823671-6c2e7cc187d9",
        idealTempMin: 15,
        idealTempMax: 35,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["None"],
        advantages: ["Pollinator magnet", "Self-sowing"],
        price: 6,
        type: "outdoor"
    },
    {
        id: "p_out_20",
        name: "Thyme",
        scientificName: "Thymus vulgaris",
        description: "Low-growing woody herb. Excellent ground cover.",
        imageUrl: "https://images.unsplash.com/photo-1629158654877-2c5544d67310",
        idealTempMin: -5,
        idealTempMax: 30,
        minHumidity: 30,
        sunlight: "direct",
        oxygenLevel: "moderate",
        medicinalValues: ["Antiseptic", "Respiratory aid"],
        advantages: ["Culinary", "Ground cover"],
        price: 6,
        type: "outdoor"
    }
];

module.exports = { indoorPlants, outdoorPlants };
