import { X, Download, Sun, Droplets, Wind } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { Button } from '../../common/Button';
import styles from '../plants/PlantDetailsModal.module.css'; // Reusing modal styles

interface HowItWorksModalProps {
    onClose: () => void;
}

export const HowItWorksModal = ({ onClose }: HowItWorksModalProps) => {

    const handleDownloadPDF = async () => {
        const element = document.getElementById('guide-content');
        if (!element) return;

        try {
            const canvas = await html2canvas(element, { scale: 2 });
            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
            pdf.save('PlantAI-Guide.pdf');
        } catch (err) {
            console.error("PDF generation failed", err);
            alert("Could not generate PDF. Please try again.");
        }
    };

    return (
        <div className={styles.overlay}>
            <div className={`${styles.modal} glass-panel`} style={{ maxWidth: '800px' }}>
                <button className={styles.closeBtn} onClick={onClose}><X size={24} /></button>

                <div id="guide-content" style={{ padding: '3rem', background: '#051810', color: '#e0e0e0', minHeight: '600px' }}>
                    <div style={{ textAlign: 'center', marginBottom: '3rem', borderBottom: '1px solid #333', paddingBottom: '2rem' }}>
                        <h1 style={{ color: '#00ff9d', fontSize: '2.5rem', marginBottom: '1rem' }}>How PlantAI Works</h1>
                        <p style={{ fontSize: '1.2rem', color: '#aaa' }}>The Science Behind Your Plant Matches</p>
                    </div>

                    <div style={{ display: 'grid', gap: '3rem' }}>
                        <section>
                            <h3 style={{ display: 'flex', alignItems: 'center', gap: '1rem', color: '#facc15', marginBottom: '1rem' }}>
                                <Sun size={28} /> 1. Temperature Aptness
                            </h3>
                            <p style={{ lineHeight: '1.8' }}>
                                Plants are living organisms with specific thermal comfort zones. We analyze the
                                <strong> 7-Day Average Temperature</strong> of your location.
                                If your local temperature falls within a plant's <code>Ideal Range</code> (e.g., 18°C - 25°C),
                                it receives a high score. Deviations cause the "Stress Score" to rise, alerting you
                                to potential dormancy or wilting.
                            </p>
                        </section>

                        <section>
                            <h3 style={{ display: 'flex', alignItems: 'center', gap: '1rem', color: '#60a5fa', marginBottom: '1rem' }}>
                                <Droplets size={28} /> 2. Carbon & Oxygen Exchange
                            </h3>
                            <p style={{ lineHeight: '1.8' }}>
                                Our simulation calculates the <strong>Photosynthetic Rate</strong> needed for human habitation.
                                By comparing a plant's metabolic class (C3, C4, CAM) with
                                standard human O₂ consumption (approx. 550 liters/day), we determine exactly
                                <em>how many plants</em> are needed to offset one person's respiration in a closed loop.
                            </p>
                        </section>

                        <section>
                            <h3 style={{ display: 'flex', alignItems: 'center', gap: '1rem', color: '#a78bfa', marginBottom: '1rem' }}>
                                <Wind size={28} /> 3. Environmental Impact
                            </h3>
                            <p style={{ lineHeight: '1.8' }}>
                                We also account for <strong>Transpiration Cooling</strong>. Plants release moisture which can
                                lower ambient indoor temperature by 1-2°C. Our algorithm favors plants with high
                                leaf surface area for hotter climates to maximize this natural cooling effect.
                            </p>
                        </section>
                    </div>

                    <div style={{ marginTop: '4rem', textAlign: 'center', fontSize: '0.9rem', color: '#666' }}>
                        Generated by PlantAI Algorithm • {new Date().getFullYear()}
                    </div>
                </div>

                <div style={{ padding: '2rem', borderTop: '1px solid rgba(255,255,255,0.1)', display: 'flex', justifyContent: 'flex-end', gap: '1rem' }}>
                    <Button variant="outline" onClick={onClose}>Close</Button>
                    <Button onClick={handleDownloadPDF}>
                        <Download size={18} /> Download Guide (PDF)
                    </Button>
                </div>
            </div>
        </div>
    );
};
