
import { jsPDF } from 'jspdf';

export const generateAndDownloadPDF = () => {
    try {
        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4'
        });

        // --- TITLE PAGE ---
        doc.setFillColor(10, 31, 22); // Dark Green Background
        doc.rect(0, 0, 210, 297, 'F');

        doc.setTextColor(0, 255, 157); // Neon Green text
        doc.setFontSize(26);
        doc.text('VanaMap Guide Book', 105, 40, { align: 'center' });

        doc.setTextColor(200, 200, 200);
        doc.setFontSize(14);
        doc.text('Caring goes smart', 105, 50, { align: 'center' });

        doc.setDrawColor(0, 255, 157); // Green line
        doc.setLineWidth(0.5);
        doc.line(40, 60, 170, 60);

        // --- CONTENT SETUP ---
        let y = 80;
        const leftMargin = 20;
        const pageWidth = 170; // Width for text wrapping

        function checkPageBreak(spaceNeeded: number) {
            if (y + spaceNeeded > 270) {
                doc.addPage();
                doc.setFillColor(10, 31, 22); // Re-apply background for new page
                doc.rect(0, 0, 210, 297, 'F');
                y = 30; // Reset Y
            }
        }

        function addSectionTitle(title: string, r: number, g: number, b: number) {
            checkPageBreak(15);
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(r, g, b);
            doc.text(title, leftMargin, y);
            y += 8;
        }

        function addParagraph(text: string) {
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(220, 220, 220); // Light gray

            // Split text to fit width
            const lines = doc.splitTextToSize(text, pageWidth);
            const height = lines.length * 5; // Approx height per line

            checkPageBreak(height + 5);
            doc.text(lines, leftMargin, y);
            y += height + 5; // Add extra spacing
        }

        // 1. Simulation Logic
        addSectionTitle('1. How the Simulation Works (AI)', 0, 255, 157);
        addParagraph('VanaMap isn\'t just a database; it IS a living simulation engine. We calculate a weighted average of your region\'s temperature for the last 30 days. We also calculate the "Respiratory Load" of your room based on the number of people vs plant oxygen output.');

        // 2. User Guide
        y += 5;
        addSectionTitle('2. For Users (Plant Lovers)', 56, 189, 248); // Blue
        addParagraph('Step 1: Detect My GPS Location - The system analyzes your local weather.');
        addParagraph('Step 2: Oxygen Simulator - Use the slider on plant pages to calculate how many plants you need.');
        addParagraph('Step 3: Nearby Shops - Find verified vendors close to you.');

        // 3. Vendor Guide
        y += 5;
        addSectionTitle('3. For Vendors (Shop Owners)', 250, 204, 21); // Yellow
        addParagraph('Step 1: Register - Select "Shop Owner" at login.');
        addParagraph('Step 2: Get Verified - Upload inventory to get a Green Tick.');
        addParagraph('Step 3: Auto-Detect GPS - Pinpoint your shop location for buyers.');

        // 4. Care Protocols
        y += 5;
        addSectionTitle('4. Advanced Care Protocols', 255, 100, 100); // Red/Orange
        addParagraph('Watering: Always check soil moisture before watering. Overwatering is the #1 killer of indoor plants. Use the finger test: top inch should be dry.');
        addParagraph('Light: "Bright Indirect Light" means the plant sees the sky but not the sun. South-facing windows are best for high-light plants; North for low-light.');

        // 5. Troubleshooting
        y += 5;
        addSectionTitle('5. System Troubleshooting', 200, 200, 200); // White
        addParagraph('Yellow Leaves: Usually a sign of overwatering or poor drainage.');
        addParagraph('Drooping: Often means the plant is thirsty, but check the soil first.');
        addParagraph('Brown Tips: Indicates low humidity. Use a humidifier or mist regularly.');

        // Footer
        checkPageBreak(20);
        doc.setFontSize(9);
        doc.setTextColor(100, 100, 100);
        doc.text('Generated by VanaMap Intelligence System • 2025', 105, 290, { align: 'center' });

        // Save using robust Blob method
        const blob = doc.output('blob');
        const url = window.URL.createObjectURL(new Blob([blob], { type: 'application/pdf' }));
        const link = document.createElement('a');
        link.href = url;
        link.setAttribute('download', 'VanaMap_Guide.pdf');
        document.body.appendChild(link);
        link.click();

        // Cleanup
        setTimeout(() => {
            document.body.removeChild(link);
            window.URL.revokeObjectURL(url);
        }, 100);

    } catch (err) {
        console.error("PDF Fail", err);
        alert("Could not generate PDF.");
    }
};
